export { default as Navbar } from './Navbar/Navbar.jsx'
export { default as Home } from './Home/Home.jsx'
export { default as About } from './About/About.jsx'
export { default as Features } from './Features/Features.jsx'
export { default as LatestSchemes } from './LatestGovernmentSchemes/LatestSchemes.jsx'
export { default as Contact } from './Contact/Contact.jsx'
export { default as Footer } from './Footer/Footer.jsx'